apiVersion: monitoring.rhobs/v1alpha1
kind: MonitoringStack
metadata:
  name: hshift-ms
spec:
  logLevel: debug
  namespaceSelector:
    matchExpressions:
      - key: hypershift.openshift.io/hosted-control-plane
        operator: Exists
  alertmanagerConfig:
    disabled: true
  prometheusConfig:
    externalLabels:
      hypershift_cluster_id: sbasabat-mgmt
      region: us-east-1
    remoteWrite:
      - queueConfig:
          batchSendDeadline: 60s
          capacity: 2500
          maxBackoff: 5s
          maxSamplesPerSend: 500
          maxShards: 1000
          minBackoff: 30ms
          minShards: 1
        url: http://token-refresher.openshift-observability-operator.svc.cluster.local
    replicas: 2
