apiVersion: monitoring.rhobs/v1alpha1
kind: MonitoringStack
metadata:
  name: hypershift-monitoring-stack
spec:
  logLevel: debug
  namespaceSelector:
    matchExpressions:
      - key: hypershift.openshift.io/hosted-control-plane
        operator: Exists
  prometheusConfig:
    externalLabels:
      hypershift_cluster_id_test: sbasabat-mgmt
      region: us-east-1
    remoteWrite:
      - queueConfig:
          batchSendDeadline: 60s
          capacity: 2500
          maxBackoff: 5s
          maxSamplesPerSend: 500
          maxShards: 1000
          minBackoff: 30ms
          minShards: 1
        url: http://token-refresher.openshift-observability-operator.svc.cluster.local
    externalLabels:
      hypershift_cluster_id_test: test-cluster
      region: us-east-1
    replicas: 2
  resources:
    limits:
      cpu: 500m
      memory: 512M
    requests:
      cpu: 100m
      memory: 256M
  retention: 1d
