apiVersion: monitoring.rhobs/v1alpha1
kind: MonitoringStack
metadata:
  name: hshift-ms
  namespace: openshift-observability-operator
spec:
  resourceSelector: {}
  namespaceSelector:
    matchExpressions:
      - key: hypershift.openshift.io/hosted-control-plane
        operator: Exists
  replicas: 2
  logLevel: debug
  retention: 1d
  alertmanagerConfig:
    disabled: true
  prometheusConfig:
    externalLabels:
      hypershift_cluster_id: d77eb6b4-a809-4f4f-a48c-7d3bb39d0f60
      region: us-east-1
      env: staging
    remoteWrite:
    - url: https://infogw-proxy.api.stage.openshift.com/metrics/v1/receive
      authorization:
        type: Bearer
        credentials:
          name: telemeter-client
          key: token
      queueConfig:
        capacity: 30000
        maxSamplesPerSend: 10000
        batchSendDeadline: 1m
        minBackoff: 1s
        maxBackoff: 256s
      writeRelabelConfigs:
      - sourceLabels: [__name__]
        action: keep
        regex: '(cluster:usage:.*|count:up0|count:up1|cluster_version|cluster_version_available_updates|cluster_version_capability|cluster_operator_up|cluster_operator_conditions|cluster_version_payload|cluster_installer|cluster_infrastructure_provider|cluster_feature_set|instance:etcd_object_counts:sum|ALERTS,alertstate=firing|code:apiserver_request_total:rate:sum|cluster:capacity_cpu_cores:sum|cluster:capacity_memory_bytes:sum|cluster:cpu_usage_cores:sum|cluster:memory_usage_bytes:sum|openshift:cpu_usage_cores:sum|openshift:memory_usage_bytes:sum|workload:cpu_usage_cores:sum|workload:memory_usage_bytes:sum|cluster:virt_platform_nodes:sum|cluster:node_instance_type_count:sum|cnv:vmi_status_running:count|cluster:vmi_request_cpu_cores:sum|cluster:kata_monitor_running_shim_count:sum|cluster:log_logged_bytes_total:sum|cluster:log_collected_bytes_total:sum|log_forwarder_output_info|log_forwarder_input_info|log_forwarder_pipeline_info|log_collector_error_count_total|log_logging_info|imageregistry:operations_count:sum|imageregistry:imagestreamtags_count:sum|eo_es_cluster_management_state_info|pod:eo_es_shards_total:max|cluster:eo_es_documents_deleted_total:sum|cluster:eo_es_documents_created_total:sum|cluster:eo_es_data_nodes_total:max|eo_es_misconfigured_memory_resources_info|eo_es_defined_delete_namespaces_total|eo_es_redundancy_policy_info|eo_es_storage_info|cluster:velero_restore_total:max|cluster:velero_backup_total:max|openshift_csi_share_mount_requests_total|openshift_csi_share_mount_failures_total|openshift_csi_share_secret|openshift_csi_share_configmap|nto_custom_profiles:count|appsvcs:cores_by_product:sum|jaeger_operator_instances_agent_strategies|jaeger_operator_instances_strategies|jaeger_operator_instances_storage_types)'
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 512M