apiVersion: monitoring.rhobs/v1alpha1
kind: MonitoringStack
metadata:
  name: hshift-ms
  namespace: openshift-observability-operator
spec:
  resourceSelector: {}
  namespaceSelector:
    matchExpressions:
      - key: hypershift.openshift.io/hosted-control-plane
        operator: Exists
  replicas: 2
  logLevel: debug
  retention: 1d
  alertmanagerConfig:
    disabled: true
  prometheusConfig:
    externalLabels:
      hypershift_cluster_id: d77eb6b4-a809-4f4f-a48c-7d3bb39d0f60
      region: us-east-1
      environment: staging
    remoteWrite:
    - url: https://infogw.api.stage.openshift.com/metrics/v1/receive
      authorization:
        type: Bearer
        credentials:
          name: telemeter-client
          key: token
      queueConfig:
        capacity: 30000
        maxSamplesPerSend: 10000
        batchSendDeadline: 1m
        minBackoff: 1s
        maxBackoff: 256s
      writeRelabelConfigs:
      - sourceLabels: [__name__]
        action: keep
        regex: cluster_version
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 512M