apiVersion: monitoring.rhobs/v1alpha1
kind: MonitoringStack
metadata:
  name: hshift-ms
spec:
  resourceSelector: {}
  namespaceSelector:
    matchExpressions:
      - key: hypershift.openshift.io/hosted-control-plane
        operator: Exists
  replicas: 2
  retention: 1d
  logLevel: debug
  alertmanagerConfig:
    disabled: true
  prometheusConfig:
    externalLabels:
      hypershift_cluster_id: sbasabat-mgmt
      region: us-east-1
    remoteWrite:
      - queueConfig:
          max_samples_per_send: 500
          batch_send_deadline: 60s
        url: http://token-refresher.openshift-observability-operator.svc.cluster.local
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 512M
  

